apiVersion: v1
kind: Service
metadata:
  name: s-landingpage-service
  namespace: staging
  labels:
    run: s-landingpage-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: s-landingpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-landingpage
  namespace: staging
spec:
  selector:
    matchLabels:
      run: s-landingpage
  replicas: 2
  template:
    metadata:
      labels:
        run: s-landingpage
    spec:
      containers:
      - name: s-landingpage
        image: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
       
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s-ingress
  namespace: staging
  annotations:
    ## Untuk menaikan batas upload file
    nginx.org/client-max-body-size: "10m"
    ## Memaksa jalan di https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
## Service Location n Characters
  - host: s-pesbuk.wibi.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: s-landingpage-service
          servicePort: 80
